/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.times2;

import org.junit.*;
import static org.junit.Assert.*;

public class LibraryTest2 {

    @BeforeClass
    public static void beforeClass() {
      sleep(5);
    }

    @Before
    public void beforeTest() {
      sleep(2);
    }

    @Test public void testOne() {
    }

    @Test public void testTwo() {
    }

    private static void sleep(int seconds) {
        try {
          Thread.sleep(seconds * 1000);
        } catch (Exception e) {
          throw new RuntimeException(e);
        }
    }
}
